/*
 * Andrea Powell
 * Centralia College : 2022 Capstone Project
 * 
 * Author Class is not yet implemented.  The plan is to use a list object to store complete names, rather than (or maybe in addition to) the comma seperated list that is generated by default.  Need to look at the current DCMI structure for Authors.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Metadata_Manager
{
   internal class Author
   {
      Guid AuthorId = Guid.NewGuid();

      private string AuthorFirstName { get; set; }
      private string AuthorLastName { get; set; }
   }
}
